Velocity-IIITDWD/iiitdwd.ac.in

app/academics/departments/ece/page.tsx
components/academics/Curriculum.tsx
data/academics.ts

Academics pages modified

---

app/globals.css
app/placements/page.tsx
components/bargraph.tsx

Mobile ver:
-Corrected bargraph, carousel and buttons

Mobile ver: Corrected bargraph, carousel and buttons

---

app/Header.tsx

The AIMS on click take you to: https://aims.iiitdwd.ac.in/aims/login/loginHome
The Students Fee portal take you to: https://www.onlinesbi.sbi/sbicollect/icollecthome.htm?corpID=873279 (SBI Collect)

fixed the header links

---

components/about/OurFamily.tsx

Adding all the  Links in the OurFamily Section

---

app/icc/page.tsx

changed font size

---

lib/utils.ts

this fixes the incorrect time shown in tenders table

change locale in utils.ts to 'en'

---

app/faculty/[id]/page.tsx
app/faculty/page.tsx

-images a passport size - 250px *by 250px

faculty images(fixed size)

---

app/(campus)/events/page.tsx
app/(campus)/magazine/MemberCard.tsx
app/Header.tsx
app/faculty/[id]/page.tsx
app/icc/page.tsx
app/nirf/page.tsx
app/placements/page.tsx
components/bargraph.tsx
components/event.tsx
components/readmore.tsx
components/ui/hover-card.tsx

Replaced html tags with next tags and fixed useEffect dependencies warnings.

Fixed warnings (merge first)

---

app/contact/page.tsx

removed more contact info link
resolves #99

removed more contact info link from contact

---

app/(campus)/events/page.tsx
app/globals.css
app/page.tsx
data/announcements.ts

- Announcements completed.
- Stats changed
#105  completed

HomePage Announcements added

---

app/academics/page.tsx

`academic_calendar_sem_1.pdf` and `academic_calendar_sem_3_5.pdf` were also added to drive at /docs

Fix links on academics page and add academic calendars

---

data/homePage.ts

adding images

---

app/(campus)/clubs/page.tsx
data/members.ts
package-lock.json

Added new clubs (cultural and technical)  , fixed the links and done some minor changes.

Addition of new clubs and fixed the links.

---

app/(campus)/clubs/page.tsx

Clubs Page Fixed

---

app/faculty/page.tsx

-media query at 3600px to align faculty list  as row flex instead of col

updated-layout-for-larger screens-4k

---

data/admissions.ts

removed deadlinks and added guidelines link

Admission page deadlinks fixes

---

app/faq/page.tsx
components/faq.tsx

updated fee link in /faq

---

app/placements/page.tsx
data/profile/committee/cgc.ts

Typo issues fixed  in placements page and changed chairman in cgc committee page

---

components/event.tsx

/events/[id] with no description removed the description heading
resolves #159 
changed components/events.tsx

removed the description heading with no description

---

app/academics/departments/cse/page.tsx
app/academics/departments/dsai/page.tsx
app/academics/departments/ece/page.tsx
app/page.tsx
components/about/OurMission.tsx
data/homePage.ts

- About page Missions error fixed
- Homepage errors fixed in programs
- Font fixed in academics

minor changes - HomePage and Academics

---

app/tenders/SortSearch.tsx

fixed search bar in tenders

---

app/contact/page.tsx

Issue165 fix

---

app/(campus)/clubs/page.tsx

Added scroll padding when clicking on any club name  from table in campus/clubs/page.tsx

Added scroll padding 

---

app/(campus)/events/page.tsx
app/admissions/btech/page.tsx
app/tenders/SortSearch.tsx

minor fixes in mobile view of search box in /tenders
closes #161

minor fixes in /tenders, /events

---

app/admissions/mtech/layout.tsx
app/admissions/mtech/page.tsx
app/admissions/phd/layout.tsx
app/admissions/phd/page.tsx

Mtech phd pages

---

app/admissions/mtech/page.tsx
app/admissions/phd/page.tsx

removing star and using different color for eligibility  

---

app/faculty/page.tsx
public/.htaccess

- removed console.log from faculty
- removed cse redirect from htaccess

minor_updates

---

app/(campus)/magazine/Issues.tsx
app/(campus)/magazine/MobileButton.tsx
app/annual_reports/MobileButton.tsx
app/annual_reports/Reports.tsx

fixes
- issue fixed with having target _blank

annual_reports and magazine page links fixed

---

.cpanel.yml
app/(campus)/magazine/Issues.tsx
app/annual_reports/Reports.tsx
public/.htaccess

fixes - 
- htaccess updated
- issues and magazine page typo fixed
- cpanel updates

some fixes

---

app/Header.tsx

Changed the Main Menu Links to text-1xl and Sub Menu Links to text-lg

Hamburger Menu Content Size Increase

---

.dockerignore
CONTRIBUTING.md
Dockerfile
README.md

```
[ ] Bugfix
[ ] Feature
[x] Build related changes
[x] Documentation content changes
[ ] Tests
[ ] Other
```
Closes #245 
- Dockerfile to mimic the production server in a docker container.
N/A

add: docker file and corresponding doc updates

---

app/careers/page.tsx

```
[x] Bugfix
[ ] Feature
[ ] Tests
[ ] Other
```
Closes #
Added a functionality to make expired job links to '#'
N/A

fix: Updated job application links to '#' for expired jobs in career page

---

public/.htaccess

```
[x] Bugfix
[ ] Feature
[ ] Tests
[ ] Other
```
Closes #
- added a redirect for /Faculty.php to /faculty
N/A

fix: added a redirect for Faculty.php

---

data/admissions.ts
data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Documentation, content changes
[ ] Tests
[ ] Other
```
Closes #
- updated admissions page and announcements
N/A

data: updated admissions page and announcements

---

data/admissions.ts

```
[ ] Bugfix
[ ] Feature
[x] Documentation, content changes
[ ] Tests
[ ] Other
```
Closes #
- content updates
N/A

release: 29-6-2024

---

data/admissions.ts

```
[ ] Bugfix
[ ] Feature
[ ] Tests
[x] Other
```
Closes #
Updated link to josaa schedule pdf along with uploading the pdf to the server
N/A

data(admissions): update josaa schedule

---

data/admissions.ts

```
[ ] Bugfix
[ ] Feature
[ ] Tests
[x] Other
```
Closes #
new release on main website
N/A

release: 7-2-2024 1

---

app/admissions/btech/page.tsx

```
[ ] Bugfix
[ ] Feature
[ ] Tests
[x] Other
```
Closes #
removed btech admission queries form
N/A

release: 3-7-2024

---

data/announcements.ts
data/homePage.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

data: update announcements, placements and homepage carousel

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
app/admissions/btech/page.tsx
data/announcements.ts
data/homePage.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - 33,34,37
Closes #
-
N/A

release 5-7-24

---

data/homePage.ts

```
[x] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - 37
Closes #
-
N/A

fix: file extension of Maincarousel7.jpeg

---

data/homePage.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
new release
N/A

release: 6-7-2024

---

data/magazine.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
fix: double name in a team in magazine.ts
N/A

release: 18-7-2024

---

data/admissions.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Data
[ ] Other
```
-
-
Changed order of quick links on btech admissions page
N/A

data(admissions): Change quick links ordering

---

data/faculty_profile.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Data
[ ] Other
```
Row ID - 58
Closes #
Updated professor's designation

Faculty designation update

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - 59
Closes #
new announcement
N/A

data(announcements.ts): added hostel announcement

---

data/admissions.ts
data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release - 26/07/2024

---

data/admissions.ts
data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Other
```
Row ID - 64,65
Closes #
-

2024 hostel update

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - 64,65
Closes #
-
N/A

Release: 30-7-2024

---

data/admissions.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
data(admissions.ts): added hostel fee link in quick links
N/A

release: 30-7-2024 2

---

data/announcements.ts
data/faculty_profile.ts
data/profile/staff.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

Release: 4-8-2024

---

data/profile/staff.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Other
```
Row ID - XX
Closes #
-Updated gopinath sir's deignation
N/A

update gopinath sir's designation

---

data/faculty_profile.ts
data/profile/staff.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

Release: 4-8-2024 2

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Data
[ ] Other
```
Row ID - 89

data(announcements): New announcement

---

data/announcements.ts
data/jobs.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: row 89

---

data/admissions.ts
data/announcements.ts
data/jobs.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - 90,91
Closes #
-
N/A

Release: 7-8-2024

---

data/admissions.ts
data/announcements.ts
data/jobs.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

Release: 7-8-2024 2

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 10-8-2024 2

---

app/globals.css
app/page.tsx
components/Marquee.tsx
data/announcements.ts

Added two links in Marquee (Row 101 102)

---

app/globals.css
components/Marquee.tsx

The Arrays size increased from 4 to 8 and  animation of marquee is increased to 50s linear infinite.

chore: reduce marquee animation speed for better readability

---

app/placements/page.tsx

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Data
[ ] Other
```
None
🔥2024 placement stats🔥

data(placements): 2024 stats update

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Other
```
Row ID - 106
Closes #
- announcement
N/A

data: announcement, row 106

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - 105,106
Closes #
-
N/A

release: 11-8-2024

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - 107
Closes #
-
N/A

release: 12-8-2024

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Other
```
Row ID - 108
Closes #
-
N/A

data(announcements): add minor program

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - 108
Closes #
-
N/A

release: 14-08-2024

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

data: announcements.ts

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 14-8-2024 3

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[XX] Other
```
Row ID - 110
Closes #
-
N/A

data(announcement.ts): updated announcement for research fellows

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - 110
Closes #
-
N/A

release: row 110

---

app/page.tsx

```
[xx] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

changed the filter method for annoucements in home page

---

app/academics/page.tsx

```
[ ] Bugfix
[xx] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
Added Minor Program in Academics Section

added Minor Programs in academics

---

app/academics/page.tsx
app/page.tsx

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 16-8-2024

---

app/announcements/page.tsx
data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Other
```
Row ID - 111,112
Closes #
- Added 2 announcements .
N/A

added-2-announcements

---

data/contactInfo.ts
data/faculty_profile.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 16-8-2024 2

---

data/faculty_profile.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Data
[ ] Other
```
116

data(faculty): Change dept

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 20-8-2024

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 21-8-2024

---

app/(profile)/chairperson/former/page.tsx

```
[ ] Bugfix
[x] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Add former chairperson's message

feat: Add former chairpersons message

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

add former chairpersons message

---

app/(profile)/chairperson/former/page.tsx

```
[ ] Bugfix
[x] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Add Smt. Sudha Murty's name in former chairperson's message

feat: Add former chairperson's name

---

app/(profile)/chairperson/former/page.tsx

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 23-8-2024

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 27-8-2024

---

data/faculty_profile.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

fix: phd university names

---

app/academics/page.tsx
data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Other
```
Row ID - 144,145
Closes #
- Added MOI to academics page
N/A

Row 144,145

---

app/admissions/mtech/page.tsx
app/admissions/phd/page.tsx

old data removal 
```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

Update old data 

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[xx] Other
```
Row ID - 163
Closes #
-
N/A

fix(annuncement.ts): removed Dr.Prakash Pawar reasearch paper

---

app/faculty/page.tsx

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

fix: dsad faculty filter

---

app/page.tsx
data/homePage.ts

```
[ ] Bugfix
[ Removed Admission Notifications and Marquee] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

Removed admission notification

---

data/faculty_profile.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Other
```
Row ID - XX
Closes #
-
N/A

Updated data in Faculty_Profile section

---

data/announcements.ts
data/faculty_profile.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 10-10-2024

---

data/faculty_profile.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Data
[ ] Other
```
Row ID - 179
Add PhD for Dr. Rajesh Kumar

data(faculty): Add PhD for Dr. Rajesh Kumar

---

app/careers/page.tsx

```
[x ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

fix: filter function for deadline in /careers

---

data/profile/staff.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 30-10-24

---

app/online/index.css
app/online/page.tsx
package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 8-11-24 2

---

data/faculty_profile.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Data
[ ] Other
```
Row ID - #200

data(faculty): Update profile for Mr Mallikarjun Kande

---

data/faculty_profile.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 26-11-24 1

---

data/tenders.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

Release: 4-12-24 3

---

data/faculty_profile.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[.] Refactoring (no functional changes, no api changes)
[ ] Tests
[ ] Other
```
Row ID - 217
Closes #
-
N/A

fix(fix): removed one faculty profile

---

data/faculty_profile.ts
data/tenders.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

Release: 13-12-24

---

data/faculty_profile.ts
data/profile/staff.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[X] Documentation content changes
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

Updated Profiles of Staff and a Faculty 

---

data/faculty_profile.ts
data/profile/staff.ts
data/tenders.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 7-12-24

---

data/announcements.ts
data/jobs.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 18-12-24

---

app/(withlayout)/tenders/Tenders.tsx
data/tenders.ts
tailwind.config.ts
types/tender.ts

```
[ ] Bugfix
[x] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

update: new indicator in tenders

---

app/(withlayout)/tenders/Tenders.tsx
data/announcements.ts
data/tenders.ts
tailwind.config.ts
types/tender.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 18-12-24 1

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 23-12-24

---

app/(withlayout)/page.tsx
data/tenders.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 23-12-24 1

---

data/faculty_profile.ts
data/tenders.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

updated : faculty_profile.ts

---

data/jobs.ts

Added details for the External Startup Incubation program by IDRP,
Verified the changes locally.

feat(jobs.ts): add external startup incubation details for idrp

---

data/tenders.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 7-1-25

---

app/(withlayout)/idrp/page.tsx

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 10-1-25

---

app/(withlayout)/idrp/page.tsx
data/jobs.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 13-1-24

---

app/(withlayout)/Header.tsx

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 15-1-25

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[x] Other
```
Row ID - XX
Closes #
-
N/A

updated announcement section

---

app/(withlayout)/Header.tsx

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 15-1-25 1

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

fix: update link for PhD and M.Tech provisional admission list

---

app/(withlayout)/Header.tsx

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 16-1-2025

---

data/tenders.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 22-1-25

---

data/jobs.ts
package.json

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 23-1-25

---

package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 23-1-25 2

---

app/(withlayout)/tenders/Tenders.tsx
data/tenders.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 24-1-25

---

data/tenders.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 25-1-25

---

data/faculty_profile.ts
data/jobs.ts
data/tenders.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 27-01-25

---

data/jobs.ts
data/profile/staff.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

chore: update application link in jobs data

---

data/faculty_profile.ts
data/jobs.ts
data/tenders.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 28-1-25

---

data/announcements.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

chore: added new announcement

---

data/homePage.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 31-1-25 2

---

data/announcements.ts
data/homePage.ts
data/jobs.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 31-1-25 3

---

app/(withlayout)/annual_reports/page.tsx
app/(withlayout)/careers/page.tsx
app/(withlayout)/faculty/page.tsx
lib/sanity/Queries.ts
migrations/MigrationFiles/contact_info.ts
migrations/utils/deleteAllDocuments.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[X] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Tests
[ ] Other
```
- Moved all the scattered queries into `/lib/sanity/Queries`.

Unify sanity queries

---

migrations/MigrationFiles/krc_data.ts
migrations/MigrationFiles/krc_dataTelFull.ts
migrations/MigrationFiles/krc_tel.ts
migrations/MigrationFiles/research.ts
migrations/utils/runAllMigrations.ts

added migrations for /krc, /acamedics

---

data/homePage.ts

```
[ ] Bugfix
[ ] Feature
[X] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

Shri Priyank Kharge visit main carousel update

---

app/(withlayout)/tenders/page.tsx
lib/sanity/Queries.ts
lib/sanity/client.ts
scripts/backupSanityData.ts

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 6-2-25

---

app/(withlayout)/tenders/Tenders.tsx

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Row ID - XX
Closes #
-
N/A

release: 7-2-25
